# Generated by Django 5.2.6 on 2025-11-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participants",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="plans.plans",
            ),
        ),
    ]
