# Generated by Django 5.2.6 on 2025-11-10 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participants",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="participants",
            index=models.Index(
                fields=["plan", "user"], name="participant_plan_id_7b55f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participants",
            constraint=models.UniqueConstraint(
                fields=("user", "plan"), name="uniq_user_plan"
            ),
        ),
    ]
