# Generated by Django 5.2.6 on 2025-11-21 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participants",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="participants",
            index=models.Index(
                fields=["plan", "user"], name="participant_plan_id_7b55f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participants",
            constraint=models.UniqueConstraint(
                fields=("user", "plan"), name="uniq_user_plan"
            ),
        ),
    ]
