# Generated by Django 5.2.6 on 2025-11-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PLAN_JOIN_REQUEST", "Plan Join Request"),
                            ("PLAN_JOINED", "Plan Joined"),
                            ("PLAN_CANCELLED", "Plan Cancelled"),
                            ("PLAN_UPDATED", "Plan Updated"),
                            ("PLAN_REMINDER", "Plan Reminder"),
                            ("PLAN_CREATED", "Plan Created"),
                            ("PLAN_LEFT", "Plan Left"),
                            ("PLAN_DELETED", "Plan Deleted"),
                            ("NEW_MESSAGE", "New Message"),
                            ("MENTIONED", "Mentioned"),
                            ("THREAD_CREATED", "Thread Created"),
                        ],
                        db_index=True,
                        help_text="ประเภทของการแจ้งเตือน",
                        max_length=50,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[("PLAN", "Plan"), ("CHAT", "Chat")],
                        db_index=True,
                        default="PLAN",
                        help_text="หมวดหมู่ของ notification (PLAN, CHAT)",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, help_text="สถานะว่าอ่านแล้วหรือยัง"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="เวลาที่อ่าน notification", null=True
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="สถานะว่าถูกลบแล้วหรือยัง (soft delete)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="เวลาที่ลบ notification", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="หัวข้อของ notification (optional)",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField(help_text="ข้อความของ notification")),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL สำหรับไปยังหน้าที่เกี่ยวข้อง",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="ข้อมูลเพิ่มเติม"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
