# Generated by Django 5.2.6 on 2025-11-15 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("plans", "0006_pinnedplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PLAN_JOIN_REQUEST", "Plan Join Request"),
                            ("PLAN_JOINED", "Plan Joined"),
                            ("PLAN_CANCELLED", "Plan Cancelled"),
                            ("PLAN_UPDATED", "Plan Updated"),
                            ("PLAN_REMINDER", "Plan Reminder"),
                            ("PLAN_CREATED", "Plan Created"),
                            ("PLAN_LEFT", "Plan Left"),
                            ("PLAN_DELETED", "Plan Deleted"),
                            ("NEW_MESSAGE", "New Message"),
                            ("MENTIONED", "Mentioned"),
                            ("THREAD_CREATED", "Thread Created"),
                        ],
                        db_index=True,
                        help_text="ประเภทของการแจ้งเตือน",
                        max_length=50,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[("PLAN", "Plan"), ("CHAT", "Chat")],
                        db_index=True,
                        default="PLAN",
                        help_text="หมวดหมู่ของ notification (PLAN, CHAT)",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, help_text="สถานะว่าอ่านแล้วหรือยัง"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="เวลาที่อ่าน notification", null=True
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="สถานะว่าถูกลบแล้วหรือยัง (soft delete)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="เวลาที่ลบ notification", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="หัวข้อของ notification (optional)",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField(help_text="ข้อความของ notification")),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL สำหรับไปยังหน้าที่เกี่ยวข้อง",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="ข้อมูลเพิ่มเติม"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="ผู้ใช้ที่ทำ action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chat message ที่เกี่ยวข้อง",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chat.chat_messages",
                    ),
                ),
                (
                    "chat_thread",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chat thread ที่เกี่ยวข้อง",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chat.chat_threads",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plan ที่เกี่ยวข้อง",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="plans.plans",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="ผู้ใช้ที่รับการแจ้งเตือน (recipient)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "is_deleted"],
                        name="notificatio_user_id_52f944_idx",
                    ),
                    models.Index(
                        fields=["user", "topic", "is_deleted"],
                        name="notificatio_user_id_93fddd_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_c62b26_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "is_deleted"],
                        name="notificatio_notific_206dea_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("notification_type__startswith", "PLAN_"),
                                ("topic", "PLAN"),
                            ),
                            models.Q(
                                (
                                    "notification_type__in",
                                    ["NEW_MESSAGE", "MENTIONED", "THREAD_CREATED"],
                                ),
                                ("topic", "CHAT"),
                            ),
                            _connector="OR",
                        ),
                        name="notification_type_topic_match",
                    )
                ],
            },
        ),
    ]
