# Generated by Django 5.2.6 on 2025-11-21 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_initial"),
        ("notifications", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="ผู้ใช้ที่ทำ action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="chat_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Chat message ที่เกี่ยวข้อง",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="chat.chat_messages",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="chat_thread",
            field=models.ForeignKey(
                blank=True,
                help_text="Chat thread ที่เกี่ยวข้อง",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="chat.chat_threads",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan ที่เกี่ยวข้อง",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="plans.plans",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="ผู้ใช้ที่รับการแจ้งเตือน (recipient)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "is_deleted"],
                name="notificatio_user_id_52f944_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "topic", "is_deleted"],
                name="notificatio_user_id_93fddd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_c62b26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "is_deleted"],
                name="notificatio_notific_206dea_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("notification_type__startswith", "PLAN_"), ("topic", "PLAN")
                    ),
                    models.Q(
                        (
                            "notification_type__in",
                            ["NEW_MESSAGE", "MENTIONED", "THREAD_CREATED"],
                        ),
                        ("topic", "CHAT"),
                    ),
                    _connector="OR",
                ),
                name="notification_type_topic_match",
            ),
        ),
    ]
