"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path

# Base directories
BASE_DIR = Path(__file__).resolve().parent.parent  # backend/backend
PROJECT_ROOT = BASE_DIR.parent  # KU-HANGOUT

# Load .env from project root
load_dotenv(PROJECT_ROOT / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-5wdu6h9okg@+*c4hh^!ddbj%cn6bi#yj6#h2xl=*p(0@fx-xtt')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []

AUTH_USER_MODEL = 'users.Users'  # App name + Model name


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'cloudinary_storage',  # Must be before django.contrib.staticfiles
    'cloudinary',  # Add Cloudinary support
    
    # Local apps
    'accounts',
    "users",
    'plans',
    'tags',
    'participants',
    'chat',
    
    # Channels for chat
    "channels",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER', 'POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'POSTGRES_PASSWORD'),
        # Prefer DJANGO_DB_* if present; else POSTGRES_*; else default.
        'HOST': (
            os.getenv('POSTGRES_HOST')
            or 'localhost'   # in Docker Compose, use service name e.g. 'postgres'
        ),
        'PORT': (
            os.getenv('POSTGRES_PORT')
            or '5432'
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT Settings - Token expiration configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # Access token valid for 7 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Refresh token valid for 30 days
    'ROTATE_REFRESH_TOKENS': False,  # Disable token rotation (requires blacklist app)
    'BLACKLIST_AFTER_ROTATION': False,  # Disable blacklist (requires token_blacklist app)
    'UPDATE_LAST_LOGIN': False,  # Disable last login update
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS settings for local development (Vite at http://localhost:5173)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://localhost:5174',  # เพิ่มบรรทัดนี้
    'http://127.0.0.1:5174'  # เพิ่มบรรทัดนี้
]
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for better frontend-backend integration
CORS_ALLOW_ALL_ORIGINS = False  # Set to True only for development if needed
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ==================== FILE STORAGE CONFIGURATION ====================

USE_CLOUDINARY = os.getenv('USE_CLOUDINARY', 'False') == 'True'

if USE_CLOUDINARY:
    # Cloudinary configuration
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    }
    
    # Ensure these are set for Cloudinary
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticCloudinaryStorage'
    
    # Cloudinary URLs
    MEDIA_URL = '/media/'
    STATIC_URL = '/static/'
    
    print("=== Cloudinary Storage ENABLED ===")  # Debug line
else:
    # Local storage
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    print("=== Local File Storage ENABLED ===")  # Debug line

# ==================== END FILE STORAGE CONFIGURATION ====================


# Redis backend for Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv('REDIS_HOST', '127.0.0.1'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

# ==================== FORCE CLOUDINARY STORAGE MONKEY PATCH ====================

print("=== FINAL STORAGE CONFIGURATION ===")
print(f"USE_CLOUDINARY: {USE_CLOUDINARY}")
print(f"DEFAULT_FILE_STORAGE: {DEFAULT_FILE_STORAGE}")

if USE_CLOUDINARY:
    # Import required modules
    import django.core.files.storage
    from cloudinary_storage.storage import MediaCloudinaryStorage
    
    # Create a new Cloudinary storage instance
    cloudinary_storage = MediaCloudinaryStorage()
    
    # Monkey patch the default_storage at module level
    django.core.files.storage.default_storage = cloudinary_storage
    
    # Also update the storage module in sys.modules to ensure it's cached correctly
    if 'django.core.files.storage' in sys.modules:
        storage_module = sys.modules['django.core.files.storage']
        storage_module.default_storage = cloudinary_storage
    
    print("✓ CLOUDINARY STORAGE MONKEY PATCHED")
    print(f"MONKEY PATCHED STORAGE: {django.core.files.storage.default_storage}")
    print(f"MONKEY PATCHED STORAGE CLASS: {django.core.files.storage.default_storage.__class__}")

# Test the storage immediately
from django.core.files.storage import default_storage as final_storage
print(f"FINAL VERIFIED STORAGE: {final_storage}")
print(f"FINAL VERIFIED STORAGE CLASS: {final_storage.__class__}")

# ==================== END FORCE CLOUDINARY STORAGE MONKEY PATCH ====================