# Generated by Django 5.2.6 on 2025-11-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PinnedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pinned Plan",
                "verbose_name_plural": "Pinned Plans",
                "ordering": ["-pinned_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plan Image",
                "verbose_name_plural": "Plan Images",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=None,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=None,
                        max_digits=11,
                        null=True,
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("max_people", models.IntegerField(default=1)),
                ("people_joined", models.IntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Saved Plan",
                "verbose_name_plural": "Saved Plans",
                "ordering": ["-saved_at"],
            },
        ),
    ]
