# Generated by Django 5.2.6 on 2025-11-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=None,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        default=None,
                        max_digits=11,
                        null=True,
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("max_people", models.IntegerField(default=1)),
                ("people_joined", models.IntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        default=" ", null=True, related_name="plans", to="tags.tags"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="plans.plans",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Image",
                "verbose_name_plural": "Plan Images",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="plans.plans",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Plan",
                "verbose_name_plural": "Saved Plans",
                "ordering": ["-saved_at"],
                "unique_together": {("user", "plan")},
            },
        ),
    ]
