# Generated by Django 5.2.6 on 2025-11-21 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pinnedplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pinned_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plans",
            name="leader_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plans",
            name="tags",
            field=models.ManyToManyField(
                default=" ", null=True, related_name="plans", to="tags.tags"
            ),
        ),
        migrations.AddField(
            model_name="planimage",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="plans.plans",
            ),
        ),
        migrations.AddField(
            model_name="pinnedplan",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pinned_by_users",
                to="plans.plans",
            ),
        ),
        migrations.AddField(
            model_name="savedplan",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by_users",
                to="plans.plans",
            ),
        ),
        migrations.AddField(
            model_name="savedplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pinnedplan",
            unique_together={("user", "plan")},
        ),
        migrations.AlterUniqueTogether(
            name="savedplan",
            unique_together={("user", "plan")},
        ),
    ]
