# Generated by Django 5.2.6 on 2025-11-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_planimage"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE plans_planimage RENAME COLUMN image TO image_url;",
            reverse_sql="ALTER TABLE plans_planimage RENAME COLUMN image_url TO image;",
        ),
    ]
