# Generated by Django 5.2.5 on 2025-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_remove_plans_tags_alter_plans_lat_alter_plans_lng_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planimage",
            name="image_data",
        ),
        migrations.AddField(
            model_name="planimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plan_images/"),
        ),
        migrations.AlterField(
            model_name="plans",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plans",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
