# Generated by Django 5.2.5 on 2025-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_remove_planimage_image_data_planimage_image_and_more"),
        ("tags", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plans",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="plans",
            name="lng",
        ),
        migrations.AddField(
            model_name="plans",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="tags.tags"
            ),
        ),
    ]
