# Generated by Django 5.2.5 on 2025-11-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_remove_plans_lat_remove_plans_lng_plans_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plans",
            name="tags",
        ),
        migrations.AlterField(
            model_name="planimage",
            name="image",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="planimage",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="plans.plans",
            ),
        ),
    ]
