# Generated by Django 5.2.6 on 2025-11-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_savedplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=None, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="plans",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=None, max_digits=11, null=True
            ),
        ),
    ]
