# Generated by Django 5.2.5 on 2025-11-14 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_remove_plans_tags_alter_planimage_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planimage",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Plan Image",
                "verbose_name_plural": "Plan Images",
            },
        ),
        migrations.AlterModelOptions(
            name="plans",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Plans"},
        ),
        migrations.RenameField(
            model_name="plans",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="planimage",
            name="image",
            field=models.ImageField(upload_to="plan_images/"),
        ),
        migrations.AlterField(
            model_name="planimage",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="plans.plans",
            ),
        ),
    ]
