# Generated by Django 5.2.6 on 2025-11-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_update_lat_lng_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_users', to='plans.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Plan',
                'verbose_name_plural': 'Pinned Plans',
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
