# Generated by Django 5.2.5 on 2025-11-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_alter_planimage_options_alter_plans_options_and_more"),
        ("tags", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="plans",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="tags.tags"
            ),
        ),
    ]
