# Generated by Django 5.2.6 on 2025-11-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
    ]
