# Generated by Django 5.2.6 on 2025-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('leader', 'Leader'), ('participant', 'Participant'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
