# Generated by Django 5.2.5 on 2025-10-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
