# Generated by Django 5.2.5 on 2025-10-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_users_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="display_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
