# Generated by Django 5.2.6 on 2025-11-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_users_display_name"),
    ]

    operations = []
