# Generated by Django 5.2.6 on 2025-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_users_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
