# Generated by Django 5.1.3 on 2025-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_change_profile_picture_to_urlfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
