# Generated by Django 5.1.3 on 2025-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_users_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]

