# Generated by Django 5.1.3 on 2025-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_users_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="social_links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

